### ISSUE TITLE
Question: How to determine the max. number of digits `encryptNumber()` will return?

### ISSUE THREAD

**Issue by anthonylau** [cyrildever/feistel-cipher#13]
I would like to have a fix length output and I can pad the output number, say `1` -> `0001`. While the `encryptNumber()` will return number with random number of digits, say input `123` -> `987654`.

Is there anyway to limit the max. number of digits or determine the max. number of digits?

**Comment by cyrildever** [comment]
Hi @anthonylau,
Actually, the library doesn't provide a way to do it directly.

You should do it yourself by using some sort of wrapping function, eg. if you want a 10-digit length number with `0` padding:
```typescript
const pad10Zero = (numberToPad: number): string => numberToPad.toString().padStart(10, '0')
const encryptedNumber = 987654
// 0000987654
console.log(pad10Zero(encryptedNumber))
```
Beware that the encrypted padded number is now a `string`, not a `number` anymore. It is just meant to be used in text, not for calculus.

Hope it helps.

**Comment by cyrildever** [comment]
Hi @anthonylau,
Unfortunately, there is no way to predetermine that considering the library don't know what's coming into it. But, normally, an incoming 6-figure number should return a 6-figure max number (considering `123456` could return `123`, ie. `000123`). Tell me if you see it otherwise.
So, it all depends on your knowledge of your incoming data.
